# Generated by Django 2.2.17 on 2020-11-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='offer_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderline',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
    ]
